repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1  # Use latest Black version
    hooks:
      - id: black
        args: ["--line-length=100"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use latest Flake8 version
    hooks:
      - id: flake8
        args: ["--max-line-length=100"]
