[tool.black]
line-length = 100
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.github
  | __pycache__
)/
'''
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]